Fix migration chain
At Hacker Hours to contribute to my first open source 
project. Tried to migrate the db locally but ran into
the following error:

ERROR:  column "meetingid" of relation "meeting_members" already exists
STATEMENT:  ALTER TABLE "meeting_members" RENAME COLUMN "meetingid" TO "meetingid"

Deleted all but the most recent migration and replaced it
with the contents of the schema. 

Note: The schema version changed. We think this means
someone forgot to commit the schema at an earlier point.